spring.application.name=jobportal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://ha7890846_jobportal:jobportal800600@jobportal.gjn9k4o.mongodb.net/?appName=jobportal
spring.data.mongodb.database=jobportalDB
#Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ha7890846@gmail.com
spring.mail.password=xidpwsqpbnkvglfw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#Exception Messages

USER_FOUND= Email registered already.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS= Invalid Credentials.
PROFILE_NOT_FOUND=Profile not found.

OTP_NOT_FOUND=OTP has been expired.
OTP_INCORRECT=OTP is incorrect.

JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Already Applied to this Job.
APPLICANT_NOT_FOUND=Applicant not found.

